version: '3.8'
services:
  backend:
    container_name: backend
    build: .
  web:
    container_name: web
    build: openresty
    ports:
      - "8001:8090"
    volumes:
      # Erforderlich, da der Container non-root läuft und Probleme mit Schreibberechtigungen hat
      - ./empty/var/run:/var/run/openresty
      - ./empty/usr/local:/usr/local/openresty/nginx/logs
      - ./openresty/nginx.conf:/etc/nginx/conf.d/nginx.conf
  sso:
    image: quay.io/keycloak/keycloak:latest
    container_name: "sso"
    volumes:
      - ./keycloak/config/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak/realms:/opt/keycloak/data/import
    command:
      - start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=demo-oidc.localhost
      - VIRTUAL_PORT=8080
    ports:
      - "9001:8080"
  samlidp:
    image: quay.io/keycloak/keycloak:latest
    container_name: "demo-samlidp.external"
    volumes:
      - ./saml/config/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./saml/realms:/opt/keycloak/data/import
    command:
      - start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=demo-samlidp.external
      - VIRTUAL_PORT=10001
      - KC_HTTP_PORT=10001
    ports:
      - "10001:10001"


